# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React App CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - "react-app/**"
  pull_request:
    paths:
    - "react-app/**"
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version-file: ./react-app/.nvmrc
        cache: 'npm'
        cache-dependency-path: ./react-app/package-lock.json
    - name: Install dependencies
      working-directory: ./react-app
      run: npm ci
    - name: Build
      working-directory: ./react-app
      run: npm run build --if-present
